# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08b7aed79dabd698444f68c396a71f455305a34efd11253cc7aef593778454104cc3830d7ae56d1d9de7f3a170bd60539d8b855cdaab04e8864c8b478ccc5819

test:
  secret_key_base: 7c72f4b47695c13ead6c45ea3a40f308eb99c8a629ac0c58dd5c6ada4dc6dbf578cc0d880ad4468c7ff31b3427feb57695642cbb8fe954a296f65af02115249c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
